fix: move config from backend to internal + support list env variables
autokitteh/autokitteh pull request #640
Opened 2024-09-10 15:05 UTC by efiShtain

- Move config from backend to internal, this is something we wanted to do before, this is a preparation for the CLI to use the same config capabilities
- Support passing env variable that parsed as list of strings
```bash
MYVAR: a,b,c 
```

```go
type Cfg struct {
  ListData []string `koanf:"myvar"`
}
```

2024-09-10 15:21 UTC, tebeka approved these changes
Approving but would love to see a test or two

2024-09-10 15:35 UTC, ig-ra requested changes
there is already similar try in config dir :)
could u please move it to internal config as well?

2024-09-10 16:27 UTC, ig-ra approved these changes

2024-10-20 12:32 UTC, tebeka commented
> * Support passing env variable that parsed as list of strings
> 
> ```shell
> MYVAR: a,b,c 
> ```

Use JSON notation for list, don't invent another serialization format.

2024-10-20 12:34 UTC, tebeka approved these changes

2025-01-19 13:34 UTC, efiShtain commented
Closing for now, 
we might re do it later

2025-01-19 13:34 UTC, closed without merging