fix: dispatcher now correctly using activities
autokitteh/autokitteh pull request #661
Opened 2024-09-13 01:10 UTC by itayd

this makes the dispatcher correctly using regular activities, and not local activities. this makes it more robust.

2024-09-14 18:00 UTC, daabr requested changes
The code itself is good, but I can't approve the logging in this PR. It is inefficient and prevents log-based analytics. The comments I left are just examples. The same issues are in all files.

2024-09-14 18:00 UTC, daabr commented on internal/backend/dispatcher/dispatcher.go
> +	sl.With("run", r).Infof("started dispatcher workflow %v for %v", r, eid)
I strongly disagree that IDs need to be in a log message - they need to be log attributes. The fact that you add them in both places is also a monitoring anti-pattern.

The whole point of structured logging is to use common messages without details, and keep the details as attributes. This allows you to group logs, build smarter analytics and monitoring (dashboard/alerts) based on messages, as well as search easily for all logs related to a specific ID with log filtering.

Furthermore, you keep using `sl.With(...).Log(...)`. This is not how sugared loggers usually accept attributes. Sugared loggers are already expensive compared regular ones, and you're creating a new sugared logger for each log message.

All of these things together are signs of bad logging.

2024-09-14 18:00 UTC, daabr commented on internal/backend/dispatcher/dispatcher.go
> +	sl   *zap.SugaredLogger
Pass a logger, not a sugared logger. This is much more performant, and you can always convert a regular logger to a sugared one when needed.

2024-09-14 18:00 UTC, daabr commented on internal/backend/dispatcher/workflow.go
> +	sl.Infof("found %d dispatch destinations for %v", len(sds), eid)
Bad log message: if it didn't contain %d and %v we could have created a dashboard for it.

2024-09-14 18:00 UTC, daabr commented on internal/backend/dispatcher/workflow.go
> +		sl.With("err", err).Errorf("could not get session data: %v", err)
Bad log message: if it didn't contain %v we could have created an alert for it.

2024-09-14 18:00 UTC, daabr commented on internal/backend/dispatcher/activities.go
> +		sl.Infof("found %d triggers for connection %v", len(ts), cid)
bad log message: without %d and %v in it we could create a custom metric for it that tracks avg/med/max no. of trigger per connection across our data (with optional filtering per attribute)

2024-09-15 06:33 UTC, daabr approved these changes
Preemptive approval - agreed to at least store in the struct logger instead of sugared logger.

2024-09-15 06:38 UTC, itayd commented
> Preemptive approval - agreed to at least store in the struct logger instead of sugared logger.

done. ftr - we agreed to try out both types of logging styles for now.

2024-09-15 06:48 UTC, merged