feat(google): refresh OAuth tokens in Go, not Python
autokitteh/autokitteh pull request #696
Opened 2024-09-26 19:20 UTC by daabr

Based on the `main` branch before PR #660

2024-09-30 09:35 UTC, tebeka requested changes
Seems unfinished. Let's talk.

2024-09-30 09:35 UTC, tebeka commented on internal/backend/sessions/sessionworkflows/oauth.go
> +	w.l.Warn("Google OAuth refresh", zap.Any("unwrap", args), zap.Any("unwrap", kwargs))
There's no actual code here.

2024-09-30 09:35 UTC, tebeka commented on runtimes/pythonrt/ak_runner/loader.py
> +        print(f"CALL LINE: {self.code_lines[node.lineno - 1]}")
Remove these.

2024-09-30 09:35 UTC, tebeka commented on runtimes/pythonrt/ak_runner/loader.py
> +        print(f"PATCHING CALL IN {self.file_name}:{node.lineno}: {name}")
Remove

2024-09-30 09:35 UTC, tebeka commented on runtimes/pythonrt/ak_runner/loader.py
> +    def visit_Import(self, node: ast.Import):
Seems like debugging code.

2024-09-30 09:35 UTC, tebeka commented on runtimes/pythonrt/py-sdk/autokitteh/google.py
> +def __google_creds_oauth2(connection: str, scopes: list[str]):
Why does the function name starts with two `_`?

2024-09-30 09:35 UTC, tebeka commented on runtimes/pythonrt/py-sdk/autokitteh/google.py
> +    # TODO: client_secret = os.getenv("GOOGLE_CLIENT_SECRET", "NOT AVAILABLE")
Add linear issue

2024-09-30 09:35 UTC, tebeka commented on runtimes/pythonrt/py-sdk/autokitteh/google.py
> +    print("NOT OVERRIDDEN!!!")  # TODO: Remove this line
Raise an exception.

2024-10-15 03:19 UTC, daabr commented
obsoleted by #714

2024-10-15 03:19 UTC, closed without merging