feat: webhook to respond with event id
autokitteh/autokitteh pull request #708
Opened 2024-09-30 23:34 UTC by itayd

2024-10-01 00:41 UTC, daabr requested changes
You shouldn't return a response body, much less with a JSON content type, unless the request explicitly contains an [Accept](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept) HTTP header.

Instead, it's much easier to add a custom HTTP header to the response, like `AutoKitteh-Event-ID` (and see [here](https://stackoverflow.com/questions/3561381/custom-http-headers-naming-conventions) about why the header *shouldn't* have an `X-` prefix).

2024-10-01 04:06 UTC, itayd commented
hmmm. will change to send data only if it accepts json.
will also add the header.

2024-10-04 03:43 UTC, itayd commented
Ended up just setting the header on response.

2024-10-04 04:02 UTC, daabr commented on internal/backend/webhookssvc/svc.go
> +	w.Header().Set("Autokitteh-Event-ID", eid.String())
There's no rule that only the first letter in header words can be capitalized, e.g. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers#websockets

```suggestion
	w.Header().Set("AutoKitteh-Event-ID", eid.String())
```

2024-10-04 04:02 UTC, daabr approved these changes

2024-10-04 21:01 UTC, merged