feat!: properly populate runtimes configurations
autokitteh/autokitteh pull request #723
Opened 2024-10-04 03:41 UTC by itayd

Allow to pass runtimes configurations.

This replaces #663 .

2024-10-06 14:01 UTC, tebeka requested changes
Please fix tests.

2024-10-06 14:01 UTC, tebeka commented on runtimes/pythonrt/pythonrt_test.go
> +	// configureLocalRunnerManager()
Remove commented code or add TODO with an issue.

2024-10-07 03:29 UTC, itayd commented on runtimes/pythonrt/pythonrt_test.go
> +	// configureLocalRunnerManager()
removed

2024-10-08 17:20 UTC, tebeka approved these changes

2024-10-09 06:20 UTC, merged