fix: race condition in python rt print
autokitteh/autokitteh pull request #796
Opened 2024-10-23 07:16 UTC by itayd

simplified mechanism, no need for additional accumulator for print and logs. just using a larger buffered channel without checking the done channel.

couldn't test it yet, ran into some trouble. @efiShtain if you can test it out that'll be great. if not I'll do it tomorrow.

2024-10-23 07:22 UTC, efiShtain commented on runtimes/pythonrt/pythonrt.go
> +		if r.doneChannel != nil {
why do you close the channel inside the loop?

2024-10-23 07:22 UTC, efiShtain commented on runtimes/pythonrt/worker_grpc_handler.go
> +	if initialCall {
initial call is implementation details of the pythonrt run 
please keep it there and not in this handler side

2024-10-23 07:22 UTC, efiShtain commented on runtimes/pythonrt/worker_grpc_handler.go
> +		select {
so technically no prints / logs until the session is done ?

2024-10-23 07:22 UTC, efiShtain commented on runtimes/pythonrt/worker_grpc_handler.go
> +			// just to check print is not full.
and if it's full ? you kill the workflow ?

2024-10-23 10:00 UTC, tebeka requested changes
In general, the amount of effort we spend on prints shows we have a serious design flaw here. It all started from the restriction that a print will be from the same goroutine that started the `Call`. If this restriction is removed a lot of hairy code can be deleted.

2024-10-23 10:00 UTC, tebeka commented on runtimes/pythonrt/pythonrt.go
> +			print:    make(chan *logMessage, 1024),
Why 1024? (vs any other number)

2024-10-23 10:00 UTC, tebeka commented on runtimes/pythonrt/pythonrt.go
> +			print:    make(chan *logMessage, 1024),
I don't see any code sending to the `print` channel. @efiShtain ?

2024-10-23 10:00 UTC, tebeka commented on runtimes/pythonrt/pythonrt.go
> +	for r := range py.channels.print {
BUG: This will block until someone closes the channel, and I don't see any code closing this channel.

2024-10-23 10:00 UTC, tebeka commented on runtimes/pythonrt/pythonrt.go
> +		if r.doneChannel != nil {
This is per item in the print channel to notify the print was handled. 
But, closing a closed or nil channel will panic, there's a race condition here if some other goroutine closes this. Not sure it'll happen though since here it's the only code that need to do that.

2024-10-23 10:00 UTC, tebeka commented on runtimes/pythonrt/worker_grpc_handler.go
> +	case <-time.After(runnerChResponseTimeout):
Related to @efiShtain's comment above. Not sure the right thing is to err if we can't add a print log.

2024-10-23 23:46 UTC, itayd commented
> In general, the amount of effort we spend on prints shows we have a serious design flaw here. It all started from the restriction that a print will be from the same goroutine that started the `Call`. If this restriction is removed a lot of hairy code can be deleted.

The root issue here is that it must be deterministic, not just from the same go routine.

2024-10-24 00:19 UTC, itayd commented
replaced by https://github.com/autokitteh/autokitteh/pull/799
@tebeka @efiShtain ptal

2024-10-24 00:19 UTC, closed without merging