allow to specify callopts, among them an easier catch syntax
autokitteh/autokitteh pull request #85
Opened 2024-03-13 09:07 UTC by itayd

not sure i like the syntax, let's discuss

2024-03-14 00:59 UTC, daabr requested changes

2024-03-14 00:59 UTC, daabr commented on examples/testprograms/http/http.star
> +
Nit: Not sure if this line was added by mistake. Unlike Google Python style, Starlark style is to have only 1 empty line between top-level blocks (at least according to Google's Bazel formatter).

2024-03-14 00:59 UTC, daabr commented on examples/testprograms/http/http.star
> +    resp, err = http1.get("https://httpbin3212.org/status/404", ak.callopts(catch=True))
This "trick" of multiple assignment happens to be supported in Python and Starlark, and sort-of in JS/TS but not so nicely. But we can't rely on it. Also, none of these options really feels "intuitive" or "easy to read".

Instead, why not just return a single `result` object that contains optional error information alongside an optional `resp` struct property, e.g. a Boolean `ok` property and/or a string `error` property.

2024-03-15 02:12 UTC, itayd commented on examples/testprograms/http/http.star
> +
```suggestion

```

2024-03-15 02:14 UTC, daabr approved these changes

2024-03-15 02:17 UTC, merged